package com.example.demo;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import com.mysite.sbb.question.QuestionService;

@SpringBootTest
class BoardWebApplicationTests {
	@Autowired
	private QuestionService qService;

	@Test
	void contextLoads() {
		qService.create("아시발 탄피", "", LocalDateTime.of(2025, 7, 9, 15, 36));
		qService.create("플로로 산화 칸타 이렇게 굴릴거면 칸타 에코는 어캐 줌?", "지금은 대충 금희 발사대로 사용중인데 이거 장막으로 바꾸면 되려나\n명함 패스 무기임 ㅋㅋㅋ", LocalDateTime.of(2025, 7, 9, 15, 35));
		qService.create("수영복 스킨 더 안 나오나", "카를로타 엉덩이 존나 꼴리는데 흠", LocalDateTime.of(2025, 7, 9, 15, 35));
		qService.create("띵잘알 형들 형들 둘중에서 뭐가 더쎄?? 투표좀", "후자가 더쎄...?\n- dc official App", LocalDateTime.of(2025, 7, 9, 15, 35));
		qService.create("아니 시발 이거 아이템 없으면 부활 안돼?", "시간 지나면 부활 이런거 없어? 솔라리스 돌파하는데 지금 1개 남았어 ㅅㅂ", LocalDateTime.of(2025, 7, 9, 15, 35));
		qService.create("2주년때 20중 복각해줌?", "아니면 2버전 캐릭들만 해줄까?", LocalDateTime.of(2025, 7, 9, 15, 34));
		qService.create("오 딱 백만 찍었다", "편안하노", LocalDateTime.of(2025, 7, 9, 15, 34));
		qService.create("수백페 승률 12분의 1임 ㅁㅌㅊ", "하아", LocalDateTime.of(2025, 7, 9, 15, 34));
		qService.create("뽑기 연출이 왜 아래에서 위로 올라오는건가 했는데", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n얘가 처음에 방랑자를 솔라리스로 떨어뜨리면서 이야기가 시작되잖아\n그 방향이 위에서 아래로 향함\n위에서 아래로 추락했더니 아래에 멀쩡한 땅덩이가 있음\n바다 아래에서 하늘로 솟구치는데\n그게 이거 아닌가 싶음\n지금 방랑자가 활동중인 솔라리스 = 대비명이 집어삼킨 (구)솔라리스의 시뮬레이션(검은 해안의 관측장치 같은) 일거같고\n아마 방랑자가 몸에 품은게 그 대비명같음. 그게 포포일거 같고\n전세대 방랑자가 포포를 그 라는 거리감이 느껴지는 인칭을 사용한게 힌트같음\n포포가 뭐든지 집어삼켜버리는 능력을 보여주는것도 그렇고\n그래서 전부 집어삼킨 대비명에서 파수인을 끄집어내듯이 공명자를 꺼내는게 아닐까?", LocalDateTime.of(2025, 7, 9, 15, 34));
		qService.create("장염 다 나아서 오늘 저녁 롯데리아 가야지", "드개재", LocalDateTime.of(2025, 7, 9, 15, 32));
		qService.create("근데 먼가 줄리아도 이대로 퇴장할거같진않은데", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n이대로 퇴장하기엔 뭔가 굉장히 찜찜한 퇴장이라 먼가 하나는 더 나올거같음", LocalDateTime.of(2025, 7, 9, 15, 32));
		qService.create("응우옌도 몬텔리에게 매수당했군", "그렇다고 난쟁이에게 죽은 5천 귀신의 원혼은 사라지지않는다", LocalDateTime.of(2025, 7, 9, 15, 32));
		qService.create("젠니가 아니라 쟈니", "쟈니", LocalDateTime.of(2025, 7, 9, 15, 31));
		qService.create("리세계 추천글에 댓글 달기 애매한게", "이거 vs 저거 뭐가 다 나아요? 는 그나마 답변 가능하지만\n뭐 필수로 가져가야 됨? 이라고 물어보면 그런건 없고 그냥 메인딜의 플레이스타일이 자기랑 맞으면 그 캐릭터랑 파츠 같이 가져가면 좋은건데\n쌩뉴비가 플레이 영상만 보고 그걸 알기가 어려워서 그렇게 말하기도 힘들다는거임..", LocalDateTime.of(2025, 7, 9, 15, 31));
		qService.create("샤콘 스토리 보고 좀 놀랐음", "사실 라군나 자체가 그렇긴한데\n이게 중국에서 통과된 스토리라는게", LocalDateTime.of(2025, 7, 9, 15, 30));
		qService.create("이 야겜 먼저 찾아준 형님한테 만원 드립니다 진짜 드립니다", "이 야겜 먼저 찾아준 형님한테 만원 드립니다 진짜 드립니다\n이 야겜은 여동생 생활이라는 게임과 비슷한 게임입니다\n하지만 그 게임과 다르게 채색이 돼있고 약간의 움직임이 있습니다\n여동생의 머리카락은 검은색이었습니다\n옷을 갈아입히거나 벗기거나 할수 있었습니다\n밤이 되면 잠따 가능했습니다\n작년에 플레이 했었는데 기억이 안나서 챗지피티 돌렸는데 이새끼도 못찾아 줬습니다\n찾아주시고 계좌 달아주시면 만원 드리겠습니다 진짜 드립니다 구라 안칩니다 엠창 깝니다", LocalDateTime.of(2025, 7, 9, 15, 29));
		qService.create("띵갤에서 인식좋은여캐가 누구임?;;;;;;;;", "플로로는 학살자\n카를로타는 약물난쟁이\n페비는 빵떡년\n파수인은 파우웅\n금희는 활공금지부터시작해서 joat\n장리는 할머니\n인식좋은여캐가없네 다들코잔가;;", LocalDateTime.of(2025, 7, 9, 15, 28));
		qService.create("[공지] 명조 워더링웨이브 갤러리 정실 투표결과", "투표결과 띵갤 정실은 ‘신이’ 누나가 되었습니다", LocalDateTime.of(2025, 7, 9, 15, 26));
		qService.create("이짤 장리가 다리 내쪽으로 뻗어서 발로 대딸해주는중일듯", "그렇게밖에 안보임", LocalDateTime.of(2025, 7, 9, 15, 26));
		qService.create("몬텔리난쟁이랑 샤콘이랑 무슨 사이임?", "?", LocalDateTime.of(2025, 7, 9, 15, 24));
		qService.create("뉴비 두번째 재혼했어...", "전 마누라들이랑은 이혼했어....", LocalDateTime.of(2025, 7, 9, 15, 23));
		qService.create("앙코는 누구 전무줌", "누구거 뺏어와야하지", LocalDateTime.of(2025, 7, 9, 15, 23));
		qService.create("완벽한 밸런스", "", LocalDateTime.of(2025, 7, 9, 15, 22));
		qService.create("페비용 섭딜은 안나오냐", "방랑자는 카르티한테 붙여서\n페비 섭딜이 없네 ㅠ  젠니는 취향 아니어서 걸렀고 페비 메인딜로 쓰고 싶은디 ㅠ  솔플은 뭔가 빡세네", LocalDateTime.of(2025, 7, 9, 15, 22));
		qService.create("유노 최대 장점", "처녀임", LocalDateTime.of(2025, 7, 9, 15, 21));
		qService.create("피살리아가 명식에 대항할때 몬텔리는 뭘한거임", "칸타렐라가 2차공명자의 힘도 반납하고 큰 그림 세우며 카르티시아를 구하려할때 카를로타는 뭐한거임", LocalDateTime.of(2025, 7, 9, 15, 20));
		qService.create("본인 스토리 봤는데 앙코 완전 개사기 아님?", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n크리스토프인지 뭔지하는 아무튼 그 잔성회 간부놈\n지금 사람들이 개사기능력이라고 마빡치고 있는데\n사실상 앙코 공명능력 하위호완 아님?", LocalDateTime.of(2025, 7, 9, 15, 19));
		qService.create("(비틱주의)", "이개씨발겜 트럭은 6전6패하고\n698원은 개같이 당첨이네\n- dc official App", LocalDateTime.of(2025, 7, 9, 15, 19));
		qService.create("샤콘 권총드는 거 첨 알음…", "얼탱", LocalDateTime.of(2025, 7, 9, 15, 18));
		qService.create("씨이발 승소산에서 살고싶다 ................", "지옥이야 현실은\n시원한 승소산에서 온천하면서 구운계란먹고 싶어\n- dc official App", LocalDateTime.of(2025, 7, 9, 15, 18));
		qService.create("이겜 리세마라 해야됌?", "한다고 치면 뭐 뽑음? 시간은 존나 많고 계정 사는 건 10~15만원 안 선에서 가능한데 되도록이면 그냥 리세 열심히 한 다음에 현질이나 하고싶음", LocalDateTime.of(2025, 7, 9, 15, 17));
		qService.create("뭘 뽑아야 할지 머리가 아프다", "지금 전도 응결 회절 인멸팟 이렇게 있는데\n인멸이 카멜2돌 산화 파수인1돌 로코코없어서 이렇게 굴리는중\n전에 칸타렐라 명함을 뽑아뒀는데 담버전 플로로를 뽑아야 할지\n아니면 이번에 영끌해서 루파 뽑고 갈브레나 존버할지 고민임..\n근데 장리랑 브1햄 둘다 없긴함 없는 속성팟 구할지 기존 팟 대체제 뽑을지가 문제임", LocalDateTime.of(2025, 7, 9, 15, 17));
		qService.create("뉴비 루파 앙코쓸건데 탑 밀기가능?", "루파 앙코 벨리나\n이렇게 쓸거고 장리는 복각소식 없고\n브렌트는 안뽑을 생각\n루파 앙코 둘다 맘에 들어서 쓰려고함\n탑이랑 해역? , 홀로그램 이런거 좋사기 에코없어도 만랩 찍으면 밀 수 있음?", LocalDateTime.of(2025, 7, 9, 15, 16));
		qService.create("권총 메인딜은 카를로타 말고 아예없었나", "이 무기는 그럼 카를 나오기전까진 왜 존재했던거임?ㅋㅋ", LocalDateTime.of(2025, 7, 9, 15, 16));
		qService.create("스토리에서 연관있는 조합이 뽕차긴 함ㅋㅋ", "그러니 유노랑 아욱국 같이 쓰게 나와야함\n저 조합으로 따로 쓴다?\n쿠로 그냥 다 죽은거임ㅇㅇ", LocalDateTime.of(2025, 7, 9, 15, 16));
		qService.create("복귀맨을 위해 장리콘을 달아주세요", "장리 새옷보고 복귀했서\n- dc official App", LocalDateTime.of(2025, 7, 9, 15, 16));
		qService.create("지하수로 여기 아직 안열린건가?", "ㅇㅇ", LocalDateTime.of(2025, 7, 9, 15, 13));
		qService.create("띵최미", "", LocalDateTime.of(2025, 7, 9, 15, 13));
		qService.create("난 창작글 안쓰기로햇음", "예전에 창작탭 비추있을때\n내글만 따라다니면서 비추10개씩 박는애 있었음\n비추가 갑자기 그렇게 늘수가 없는데 념글막을려고 다중이써서 10개씩 비추박더라\n그렇게 내 창작글이 싫엇나봐..그래서 똥글만 싸는중임", LocalDateTime.of(2025, 7, 9, 15, 13));
		qService.create("양양 편지 요약기능 도입 시급함", "편의성패치 최우선 과제로 삼아야함..", LocalDateTime.of(2025, 7, 9, 15, 13));
		qService.create("띵최미", "양양", LocalDateTime.of(2025, 7, 9, 15, 12));
		qService.create("갈브레아가 메인 딜러면 좋겠다", "불 파티도 이제  스근하게 해볼려고 루파 뽑았는데  찌라시 그대로면 갈브레아 뽑긴 할듯\n(장리 브렌트 관심없어서 안했고 다른 속성 파티 만듬 저때 그리고 앙코는 잇음ㅋㅋ)", LocalDateTime.of(2025, 7, 9, 15, 9));
		qService.create("띵조도 호요랩처럼 폰에 위젯있음?", "폰으로 플레이트확인하구시퍼.....", LocalDateTime.of(2025, 7, 9, 15, 9));
		qService.create("게임에 고아가 너무 많다", "스토리 보면 부모있는 년이 제일 희귀함…", LocalDateTime.of(2025, 7, 9, 15, 9));
		qService.create("욕 좀 그만하면 안될까 얘들아..", "씨발 욕좀 적당히하라고 개색기들아", LocalDateTime.of(2025, 7, 9, 15, 9));
		qService.create("카를로타 키가 120정도 되나?", "15센치 굽 신고 140이니까 120보단 조금 클려나", LocalDateTime.of(2025, 7, 9, 15, 8));
		qService.create("상자파먹기 유튭 보고 따라하니까 머리아프다", "창모드로 카를로타사이즈로 명조하니까 어지럽다\n걍 맵스보면서 해야할지도", LocalDateTime.of(2025, 7, 9, 15, 7));
		qService.create("2버전 후반부 트레일러 다시 보는데", "갈브레나 귀걸이 뱀장식 + 배경이 도시 아래 구렁텅이네\n무엇을 의미하는거지", LocalDateTime.of(2025, 7, 9, 15, 6));
		qService.create("정말고민이많다", "지금 지갑사정이 좋지 않아서 루파를 뽑아도 전무를 못 가져갈 것 같은데 그냥 걸러야하나", LocalDateTime.of(2025, 7, 9, 15, 4));
		qService.create("다음 스토리 보고싶어서 울었어", "로로언제나와", LocalDateTime.of(2025, 7, 9, 15, 4));
		qService.create("딸치고 나서 코액 나만 걍 팬티로 닦음?", "차피 말라서 그대로 세탁기에 넣는데\n- dc official App", LocalDateTime.of(2025, 7, 9, 15, 3));
		qService.create("뉴비 계정 질문좀", "루파 개꼴려서 시작함\n출시때 리세만하다가 접었어서 원래 계정에 앙코 감심 벨리나 기염 루파만있는데\n이계정 그냥 쭉 하는게좋아 아니면 새계정 파서 장리 먹고가는게 좋아?", LocalDateTime.of(2025, 7, 9, 15, 3));
		qService.create("혐) 페비 학대", "", LocalDateTime.of(2025, 7, 9, 15, 3));
		qService.create("님대체뭘보러온건지말하셈", "완장 똥싼거 인증", LocalDateTime.of(2025, 7, 9, 15, 3));
		qService.create("지금까지의 스토리로 봤을땐 세계관 최강자가", "누구인가여 전성기까지 따지면 방은우인데 현재는 잘 모르겠네요", LocalDateTime.of(2025, 7, 9, 15, 3));
		qService.create("개재용 이거마렵네", "수백페 사기치지마라", LocalDateTime.of(2025, 7, 9, 15, 0));
		qService.create("방랑자와 리나시타의 성녀들", "https://www.pixiv.net/artworks/130175693", LocalDateTime.of(2025, 7, 9, 15, 0));
		qService.create("기랑자-샤콘 퀵스왑 연습 부작용", "샤콘이 또 생각보다 쎄서 둘이 퀵스압하면서 필드 사냥하게 되고\n그러다보니깐 기랑자 에코도 카르띠꺼 만들다 남은거 입고있는데 맞춰주고싶어짐\n하 젠장..", LocalDateTime.of(2025, 7, 9, 14, 59));
		qService.create("왜 자꾸 젠니 풀돌은 페비 2돌까지 해야 다른 딜러 풀돌급이라 하냐", "젠페 안 써봤나", LocalDateTime.of(2025, 7, 9, 14, 58));
		qService.create("뉴비면 로코코도 뽑는게 좋음?", "인랑자 말고는 메인딜이 없어서 플로로는 뽑을건데", LocalDateTime.of(2025, 7, 9, 14, 57));
		qService.create("1돌권 모았는데 누구한테 줘야대냐 못참고 가챠권 바까먹기 전에 써야하는데", "- dc official App", LocalDateTime.of(2025, 7, 9, 14, 56));
		qService.create("금희 젖통 jpg.", "", LocalDateTime.of(2025, 7, 9, 14, 56));
		qService.create("우으 고기 먹고싶어 우으..", "고기..", LocalDateTime.of(2025, 7, 9, 14, 51));
		qService.create("공효 제한은 없음??", "그냥 높으면 높을수록 공명에너지 빨리 참??\n최대 한계는 없나?", LocalDateTime.of(2025, 7, 9, 14, 51));
		qService.create("인멸랑자는 현역이 맞지", "와이프 ㅈㄴ 많고 꼴리는대로 가져가도됨.", LocalDateTime.of(2025, 7, 9, 14, 51));
		qService.create("여기 버튼이 있습니다", "이 버튼을 한번 누를 때마다 플로로의 가슴이 0.1%커집니다\n대신 야귀군이 한명씩 죽을거야", LocalDateTime.of(2025, 7, 9, 14, 50));
		qService.create("캐릭터 엉덩이 보기 좋은 장소 추천좀", "벽에 매달렸을 때 잘보이는 그런 위치 있잖아\n원신은 개꿀자리 아는데 이 겜은 몰라서 그럼", LocalDateTime.of(2025, 7, 9, 14, 49));
		qService.create("제니 풀돌하면 페미버림??", "딜 잘나옴??", LocalDateTime.of(2025, 7, 9, 14, 48));
		qService.create("인멸랑자 아직도 현역이네", "기랑자로 한줄 알았는데 인멸랑자네\n기랑자는 풀돌 풀재 풀어주는거 아닌이상 시도는 못해볼듯?", LocalDateTime.of(2025, 7, 9, 14, 47));
		qService.create("저 사실 몬텔리 지지함", "피살리아를 믿지 마", LocalDateTime.of(2025, 7, 9, 14, 47));
		qService.create("이중에 누가 제일 꼴림?", "난 앙코가 제일 꼴리는데 매 번 방랑자 오빠라고 불러줘서 그런가", LocalDateTime.of(2025, 7, 9, 14, 46));
		qService.create("아직도 띵조 메인 스토리 1도 이해못함", "ㄹㅇ", LocalDateTime.of(2025, 7, 9, 14, 45));
		qService.create("컴퓨터 1도 몰라서그러는데", "이거면 명조 잘돌아감?ㅜㅜ\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 45));
		qService.create("우우.... 띵부이... 우럿떠..", "에코런 돌기 귀찮아서 우럿떠....\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 44));
		qService.create("저번주에 김범룡 노래 듣는다니까 딸피 소리 들었음", "바람바람바람 외에도 현아, 카페와 여인, 바람만 알지 등 좋은 노래 많은데", LocalDateTime.of(2025, 7, 9, 14, 44));
		qService.create("보상 다 먹은 이벤트는", "제일 아래로 좀 치워주면 좋겠다... 거슬리네", LocalDateTime.of(2025, 7, 9, 14, 44));
		qService.create("언젠가 해야지 생각만하고 엄두못내고잇는거", "마음의 영역 스토리 정리\n쉽지아늠", LocalDateTime.of(2025, 7, 9, 14, 43));
		qService.create("필드는 돌고돌아 로코코로 귀결되네", "❤+❤+❤+❤+‼+‼+‼+이젠 폭풍제조기 없이는 살 수 없는 몸이 되어버려어어엇‼+‼+‼+❤+❤+❤+❤+", LocalDateTime.of(2025, 7, 9, 14, 43));
		qService.create("클로로 몇돌파하지", "가성비인 2돌파까지만 해야겠다\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 43));
		qService.create("아 자꾸 2페에서 뒤지네", "", LocalDateTime.of(2025, 7, 9, 14, 40));
		qService.create("루파 뭔가 표독 한녀처럼 생김", "ㄹㅇ", LocalDateTime.of(2025, 7, 9, 14, 40));
		qService.create("백종원처럼 되버린 방랑자.", "", LocalDateTime.of(2025, 7, 9, 14, 40));
		qService.create("늦은 6돌", "좆같은 새끼... 좀 날래날래 튀어나와라.\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 39));
		qService.create("겨드랑이에 양파 쉰내나는데 어캄?", "ㅈ되네..\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 39));
		qService.create("명조 때문에 sk -> kt 로 넘어가는거 어찌 생각함", "버전마다 1~2트럭 정도만 지르는 중소과금인데\n메리트 있어보임?", LocalDateTime.of(2025, 7, 9, 14, 39));
		qService.create("이게 꼴리는거보면 페도는아닌듯", "- dc official App", LocalDateTime.of(2025, 7, 9, 14, 38));
		qService.create("사람들이 띳도그 왤케 쓰나 했더니 돈 주는구나", "이걸로 유행시키는 거였네\nㄹㅇ 트럭 질러야지", LocalDateTime.of(2025, 7, 9, 14, 38));
		qService.create("에코 캘까", "띳띠 1000차이로 50000안되는거 진짜 거슬리네\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 37));
		qService.create("그대여~ 아무 걱정 하지 마라요~~", "우리 하암께~~ 노오래 하압시다~", LocalDateTime.of(2025, 7, 9, 14, 37));
		qService.create("공방 공지올리라햇다", "숨참는다", LocalDateTime.of(2025, 7, 9, 14, 36));
		qService.create("이거 에코 이벤 왤캐 지루하냐", "6렙에 가속 풀리면 좀 낫냐", LocalDateTime.of(2025, 7, 9, 14, 33));
		qService.create("허상에서 고릴라잡는데 샤콘이 사라져", "샤콘이 배경에서\n이러고 있는데\n고릴라가 그로기 걸리면 노래하던 샤콘이 사라져버려\n모듈때문은 아닌거같은데 회랑자 써야해?", LocalDateTime.of(2025, 7, 9, 14, 32));
		qService.create("말 할 수 없는 이유로 똥 마려워짐 !!", "", LocalDateTime.of(2025, 7, 9, 14, 32));
		qService.create("우우..띵붕이", "피쌌어..", LocalDateTime.of(2025, 7, 9, 14, 32));
		qService.create("말할이유로기분안좋아짐ㅋㅋㅋ", "7시에 겨우 빨리 일어났는데 10시쯤에 존나 졸려져서 다시 자버리고 수면패턴 또 씹창남ㅋㅋㅋㅋㅋㅋ", LocalDateTime.of(2025, 7, 9, 14, 31));
		qService.create("에코딸깍하면서 먹을 점심메뉴추천받음", "", LocalDateTime.of(2025, 7, 9, 14, 31));
		qService.create("모발겜 기준이라 그런지 레이트레이싱 사양도 별로 안먹네", "트리플A급 패키지겜들 대비 그만큼 티도 적게 나지만\n사양도 퍼포먼스급이면 프레임 드랍도 없이 무난하게 잘 돌아간다\n최적화 빙신같았다고 욕많이 먹었는데 이정도면 ㄹㅇ 존나 빡시게 일해서 고친듯", LocalDateTime.of(2025, 7, 9, 14, 30));
		qService.create("루파 꼴에 뽀찌는 괜찮아서 매너40연 함", "이 개씹씹버러지같은 명조4성들중 유일한 정상인 산화머니 1개밖에 안뜨는거보고 개좆같음을 느낌\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 30));
		qService.create("샤콘 괜히 뽑앗네", "띳띠 풀돌하니까 그냥 솔플하는게 더 클탐 빠른기분", LocalDateTime.of(2025, 7, 9, 14, 29));
		qService.create("말못할이유로기분좋아짐 ㅋㅋㅋㅋㅋ", "이유는 절대말못해!!", LocalDateTime.of(2025, 7, 9, 14, 28));
		qService.create("신 기류셋 이거말한건가", "진짜 에코셋 이대로 나온다치면 유노는 기류 칸타 포지션일수도", LocalDateTime.of(2025, 7, 9, 14, 28));
		qService.create("깃발 구역3에 보물상자 어케먹음?", "수영장처럼 되있는데 지하에 있는거같은데 들어갈 구멍이 안보임 ㅇㅇ", LocalDateTime.of(2025, 7, 9, 14, 27));
		qService.create("이제 뽑을거 \"신코코\"\"유노\"\"치사\"뿐이네", "말고는 광학설거지뿐임", LocalDateTime.of(2025, 7, 9, 14, 27));
		qService.create("아니 루파 마지막 컷씬은", "전투섹스 하러 달려가는\n한마리의 미친 늑대같음", LocalDateTime.of(2025, 7, 9, 14, 27));
		qService.create("반천 초회깰까 3.7 패키지 제외 풀매수 할까", "쿠폰 없어서 깡으로 박아야 할 것 같은데", LocalDateTime.of(2025, 7, 9, 14, 27));
		qService.create("신인멸 기대되는게", "로코코도 좋은데 걍 그자리에 풀돌 카멜들어가도 역시너지 나진 않을거 같아서 재밌을 거 같음\n근데 2돌 로코코 들어가는게 더 쎈가?", LocalDateTime.of(2025, 7, 9, 14, 27));
		qService.create("갑자기 기분이 막 좋아짐 ㄹㅇ...", "삼성을 찬양하고싶고 에픽게임즈가 우습게 보임", LocalDateTime.of(2025, 7, 9, 14, 26));
		qService.create("장브루 중에 장리만 없으면 어떤 파티 만들 수 있음?", "브렌트 루파 둘 다 있는데 장리만 없음 파티 만들 수 있는 거 있음?", LocalDateTime.of(2025, 7, 9, 14, 26));
		qService.create("젠페 복각은 한 2.7쯤에 할라나", "지금부터 2.7까지 존버해서\n젠페 갖고오고 치사 뽑으면 완벽하다", LocalDateTime.of(2025, 7, 9, 14, 26));
		qService.create("아우구스타 뽑느냐는 그거에 달렸음", "두발을 땅에 붙이고 맛있게 패냐\n아니면\n공중에서 흐느적 거리냐\n플로로도 처음에 증폭기라\n증폭이 종특 공중 허우적 일거같아서 거르려고 했는데\n유출보니까 꽤 맛있게 나왔더라\n왠만하면 뽑을듯", LocalDateTime.of(2025, 7, 9, 14, 25));
		qService.create("로로 써본 게이들 있음?", "체감 어떰? 기존 캐릭이랑 차별점 느껴짐?", LocalDateTime.of(2025, 7, 9, 14, 25));
		qService.create("유튭에 명조 컷신 올라온거 보면서 눈물 흘렸는데", "엄마가 뭘 그렇게 슬프게 보니~ 이러길래 아 방 염탐하지 말라고!!이러고 화냈다 개짜증나 진짜\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 24));
		qService.create("지금 스즈메 없음??", "카르띳띠 에코 파밍해야하는데 신비한경지 어디서 들어가야하는거임??\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 24));
		qService.create("남자같은 여캐 VS 여자같은 남캐", "하나 뽑아야한다면 누구뽑음", LocalDateTime.of(2025, 7, 9, 14, 23));
		qService.create("치사 융융이라고 치면 루파 뽑아야대나?", "멀로나올깡 궁금행", LocalDateTime.of(2025, 7, 9, 14, 23));
		qService.create("2주전 공방할줄 알앗는데", "이럼 1주전에하나", LocalDateTime.of(2025, 7, 9, 14, 23));
		qService.create("갤스 나오고부터 명조에 417만원 썼노", "쿠폰이랑 페이백같은걸로 이득본거도 추가로 10트럭이상은 되네\n갤스 나오기전엔 도대체 어케 살았지", LocalDateTime.of(2025, 7, 9, 14, 21));
		qService.create("챗지피티 똑똑하네", "노래까지 찾아주는구나", LocalDateTime.of(2025, 7, 9, 14, 21));
		qService.create("수백패 가격싼 패키지는 확률주작 안하네..", "트럭은 한번도 안걸려봤는데..", LocalDateTime.of(2025, 7, 9, 14, 20));
		qService.create("이새끼들 이메일 변동된거를 말안해주네", "이메일 변동완료된줄 모르고 전 이메일로 로그인하는데 가입안된 계정이라길래 뭔가했네 ㅅㅂ 네이버 연동 안해놨으면 ㅈ될뻔했노", LocalDateTime.of(2025, 7, 9, 14, 19));
		qService.create("알면서도 속아야하네 씨발 아", "2줄깠더니 공퍼 크리?ㅋㅋ 뒤졌다 하고 3줄 한번에 더깠는데 하", LocalDateTime.of(2025, 7, 9, 14, 18));
		qService.create("가만보면 공명자들 개사기꾼들이잖아", "에코로 변신해서 즐기는 이종간이라니", LocalDateTime.of(2025, 7, 9, 14, 17));
		qService.create("젠니 야근하는게 단순히 돈때문임?", "밤일 보조알바하면 더 버는거 아니냐\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 17));
		qService.create("내가 왜 풀충을 했을까", "시벌~ 깡체 깡방 ㅈ도 의미없는 피증 뽑으려고 600별소를 땅에 처 버렸노 ㅋㅋㅋㅋㅋ 코코이나 쳐야지 아", LocalDateTime.of(2025, 7, 9, 14, 17));
		qService.create("근데 플로로 가슴커지는거 자연스러운거아님?", "성장기 소녀아님? 안그래도 성장기라 커지는데\n섹스도 하니 더 커질수도잇지", LocalDateTime.of(2025, 7, 9, 14, 14));
		qService.create("씹덕들도 코스어한테 막찝적대고 그럼?", "현실여자한테 별로 관심없는거 아니었노\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 14));
		qService.create("지금 시작해서 스토리 따라잡으려면 얼마정도 플레이 해야함?", "하루 세시간 정도하면 한 이삼주 걸림?\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 14));
		qService.create(".", "", LocalDateTime.of(2025, 7, 9, 14, 13));
		qService.create("젠니가 진짜 풀돌해도 병신임 ㅋㅋ", "", LocalDateTime.of(2025, 7, 9, 14, 13));
		qService.create("내일부터 또 이벤트라니 무무기획최고", "ㅅㅅㅅ", LocalDateTime.of(2025, 7, 9, 14, 12));
		qService.create("플로로 이 모션들 넘 멋짐", "점공 순간 헤카테로 변해서 앞에 후리는 거랑\n공스? 같은 거 쓰면 뒤 보고 걷는 거 ㄹㅇ 간지 좆됨", LocalDateTime.of(2025, 7, 9, 14, 12));
		qService.create("무기스킨 이건 언제준거지", "저기 처음눌러봤는데 저런게있네 배포였나", LocalDateTime.of(2025, 7, 9, 14, 12));
		qService.create("뉴비 30별 아다깸", "중앙탑 1층이 개빡셌음", LocalDateTime.of(2025, 7, 9, 14, 11));
		qService.create("간식 추천좀 오레오쿠키vs메르바쿠키vs그냥참기", "ㅈㄱㄴ\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 11));
		qService.create("띳도그 작작해 주긴다", "아란냐?\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 11));
		qService.create("ㄹㅇ Y컵이래", "", LocalDateTime.of(2025, 7, 9, 14, 11));
		qService.create("방금 못볼걸 봤어 ㅠㅠ", "나만 볼 수 없는데 이걸 어떻게 하지\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 10));
		qService.create("ㄴ띳도그 맛집", "- dc official App", LocalDateTime.of(2025, 7, 9, 14, 10));
		qService.create("쿠로게임즈 죽을래?", "빨리 내 별소 450개 내놔 30별했는데 왜 250개만 주냐고 아오 문의 답변 언제와", LocalDateTime.of(2025, 7, 9, 14, 10));
		qService.create("내가죽였냐?", "내가 죽였어 ㅋ", LocalDateTime.of(2025, 7, 9, 14, 10));
		qService.create("...", "", LocalDateTime.of(2025, 7, 9, 14, 8));
		qService.create("니들 캐릭터 포지션 많이신경쓰는편임??", "난 모션잘뽑고 온필드시간만 적당히 잘보여주면\n멘딜이든 섭딜이든 힐러든 안가리는편인데\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 7));
		qService.create("아 스토리컷신 ost 진자 좋내", "먼가 척추서는 감성임", LocalDateTime.of(2025, 7, 9, 14, 6));
		qService.create("유두절에 안부 인사 올립니다", "하우 두 유 두?\n엌ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 6));
		qService.create("플로로 아직도 감감 무소식임?", "재료 언제뜸", LocalDateTime.of(2025, 7, 9, 14, 5));
		qService.create("카멜 3돌이상인사람 플로로 몇돌할거임?", "조합이 파수인 안껴도되는 장점은 있긴하던데", LocalDateTime.of(2025, 7, 9, 14, 4));
		qService.create("요즘 루파 볼때마다 임신시키고싶음", "임신하고 애 생겨서 조신해진 루파가 보고싶음\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 4));
		qService.create("ㄴ주어가 띳도그로 바뀜", "", LocalDateTime.of(2025, 7, 9, 14, 4));
		qService.create("하이퍼캐리팟은 애무구간이 지루해", "서폿 섭딜들 애무하면서 예열하는게 루즈하달까\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 3));
		qService.create("이번 버전 멀티이벤트 하나도 없었나?", "너무 심심한데\n멀티 이벤좀 내주지", LocalDateTime.of(2025, 7, 9, 14, 2));
		qService.create("초회정도만 털어먹는 유저면", "2돌파 재화권 사지 말고 걍 뽑기권이나 살까", LocalDateTime.of(2025, 7, 9, 14, 2));
		qService.create("게임할시간 없어서 그런데 월정액만 지르고", "하루 1분 접속해서 보상만 받는거 어떰\n손핸가", LocalDateTime.of(2025, 7, 9, 14, 2));
		qService.create("이해안가는 공명 어빌리티 1짱", "개좆묑\n그래서 구체적으로 뭐 하는 능력인지 글로 알 수가 없음", LocalDateTime.of(2025, 7, 9, 14, 1));
		qService.create("장루브 파티 태그액션 하위호환", "장루브 파티가 ㅈ으로 보이냐? - 개추\n그래도 마블은 못비비지 - 비추\n- dc official App", LocalDateTime.of(2025, 7, 9, 14, 1));
		qService.create("띵조는 일을 열심히 하는건가?", "얘네들 대체 뭘 하길래 들어갈때마다 업데이트임", LocalDateTime.of(2025, 7, 9, 14, 1));
		qService.create("jpop이나 겜브금 들으면서 폐허 치는게 낙이다", "https://www.youtube.com/watch?v=aRDURmIYBZ4\nhttps://www.youtube.com/watch?v=q2DBeby7ni8\nhttps://www.youtube.com/watch?v=X70m65dSM7g\nhttps://www.youtube.com/watch?v=2765cJ8uUZo\n으흐흐", LocalDateTime.of(2025, 7, 9, 14, 0));
		qService.create("명조 역대 최고 미녀 투표", "- dc official App", LocalDateTime.of(2025, 7, 9, 14, 0));
		qService.create("페비 사지절단순애강간 짤", "야\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 58));
		qService.create("본인 이제 전도(유기) 제외하면 광학 응결남앗음", "젠페는 이미 이상효과니 뽑으면되고\n응결팟은 신 응결 먼저 나와서 카를로타랑 둘중에 좋은거 선택할수있앗음 좋겟음", LocalDateTime.of(2025, 7, 9, 13, 58));
		qService.create("이쁜페비그림특징", "페비가아님", LocalDateTime.of(2025, 7, 9, 13, 57));
		qService.create("루파가 많이 꼴리긴한가봄", "내주변애들 장브없어도 루파 명전들어가고보네ㅋㅋ\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 57));
		qService.create("지금 리세계로 시작하기에 ㅈㄴ좋은듯", "카르티시아 명전 샤콘으로 시작하면\n1파티 그냥 완성인데\n돈좀 지른다 치면 인멸팟 용융팟 골라잡고 2파티 만들 수 있고\n천천히 해도 2파티 필요한 시점에 아웃국 유노 모은재화로 뽑으면 됨\n파츠 팔이 본격화 하면서 파츠를 계속 붙여서 내주니까 파티완성이 바로바로 되는게 진짜 좋은듯", LocalDateTime.of(2025, 7, 9, 13, 56));
		qService.create("유노가 왜 강공일거라 생각함 ㅡㅡ", "해방일 수도 있음", LocalDateTime.of(2025, 7, 9, 13, 55));
		qService.create("장루브는 다른 파티랑 느낌이 다름", "여타 파티는 메인딜러 몰아주는 느낌이라\n따까리 사이클 -> 따까리2 사이클 -> 메인딜 무대 같은데\n장부르는 멤버 세 명 다 \"딜ㅅㅌㅊ\" + \"모션이 전투적임\" 겹쳐서 그냥 메인딜러 세 명 스왑하면서 싸우는 느낌같음\n차례대로 나와서 패는 느낌\n플칸로 나오면 얘네도 장르부 느낌 날것같음", LocalDateTime.of(2025, 7, 9, 13, 55));
		qService.create("차기 대한민국 대통령은 파수인이다", "반박안받음", LocalDateTime.of(2025, 7, 9, 13, 54));
		qService.create("띳띠 변신 전 키는 몇임?", "난쟁이보단 커보이던데 150초반인가", LocalDateTime.of(2025, 7, 9, 13, 54));
		qService.create("이상태에서 띳띠랑 쓸수있는거없음?", "카로파만 계속쓰니까 질림\n띳띠 써보고싶은데 뭐 같이쓰면좋은애들 없음?\n걍 아무거나 넣고 써야하나\n필드용인데 필드도 어려워서 지금", LocalDateTime.of(2025, 7, 9, 13, 54));
		qService.create("근데 미아가 돈이 필요하다고 한 이유가 뭐임?", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n미아가 돈 필요해서 귀족들한테 몸 파는 히토미 망상하라고 던져준 대산가?", LocalDateTime.of(2025, 7, 9, 13, 54));
		qService.create("방파제로 삼행시해보겠습니다", "방순이\n파우웅\n제 아내들임\n감사합니다.", LocalDateTime.of(2025, 7, 9, 13, 52));
		qService.create("띳띠 유입인데 에코 둘 중 어떤거 쓰는게 나음?", "걍 다시 에코작해서 유효옵 띄운느게 나음?", LocalDateTime.of(2025, 7, 9, 13, 51));
		qService.create("오늘 저녁은 루파팡으로 결정", "띳띠가 조아해요", LocalDateTime.of(2025, 7, 9, 13, 50));
		qService.create("귀여운 애가 귀여운 거 보고 귀엽다하는 콘", "", LocalDateTime.of(2025, 7, 9, 13, 49));
		qService.create("새 기류셋 보면 유노 파수인은 아닐거같은데", "4코메인옵 기류딜12퍼 강공12퍼인데다 딜계수도 있고 그냥 브렌트 칸타처럼 힐이 달린 섭딜로 나올거같은데", LocalDateTime.of(2025, 7, 9, 13, 49));
		qService.create("너희 에어컨의 원리를 아니", "에어컨 안에는 냉매가 있는데 말이야\n뭔가가 액체에서 기체가 되면 열을 가둬버린단 말이야\n그래서 실외기에서 기체를 액체로 압축해서 실내로 보내면 자연스럽게 기화되면서 차가워진다는 말이야\n이걸 이용해서 공기를 차갑게 하는게 에어컨이다 이말이야", LocalDateTime.of(2025, 7, 9, 13, 47));
		qService.create("새알심이랑 야스하는 짤", "님", LocalDateTime.of(2025, 7, 9, 13, 47));
		qService.create("설문조사 냈다", "이렇게 하면 되는거지?", LocalDateTime.of(2025, 7, 9, 13, 44));
		qService.create("정실?", "그야 페비인 게 상식이잖아 띵붕아 대체 무슨 소리를 하는 거야", LocalDateTime.of(2025, 7, 9, 13, 41));
		qService.create("루파 뽑을까요?", "장리 복각하면 무조건 뽑을 생각이고 브렌트는 뽑을 생각이 없는데 루파 뽑고 가는게 좋을까요?", LocalDateTime.of(2025, 7, 9, 13, 41));
		qService.create("옆집 pv 나왔네", "조금만 놀다올게", LocalDateTime.of(2025, 7, 9, 13, 40));
		qService.create("맵 파먹기 << 이거 맵스 필수임?", "아님 인겜 보물탐지기로 충분하나?", LocalDateTime.of(2025, 7, 9, 13, 40));
		qService.create("아 수백페에 기대지 말걸", "귀찮다고 수백페 한번만 뜨면 이득이다고 패키지 질렀는데 한번을 안뜨네", LocalDateTime.of(2025, 7, 9, 13, 40));
		qService.create("뉴비는 방파제 듀오 못뽑음?", "얘네 뽑을 수 있음??", LocalDateTime.of(2025, 7, 9, 13, 39));
		qService.create("앙코 아크릴 드디어 왔다ㅋㅋㅋㅋㅋㅋㅋㅋ", "작년 12월에 주문해서 언제오냐고 징징거렸던 아크릴이 드디어왔다\n캬ㅋㅋㅋㅋㅋㅋㅋㅋㅋ", LocalDateTime.of(2025, 7, 9, 13, 39));
		qService.create("지금 에어컨 키고 띵조하면서 아이스크림 먹는데", "몇타치임?", LocalDateTime.of(2025, 7, 9, 13, 38));
		qService.create("파수인 <- 수천년동안 버그한번 안일으킴", "심지어 유지보수도 없엇는데 스스로 감정까지 생성할 정도로 진화함\n파수인 만든 개발자는 신이다", LocalDateTime.of(2025, 7, 9, 13, 37));
		qService.create("명조만 키면 방 사우나되네", "에어컨 없으면 컴조 못할듯", LocalDateTime.of(2025, 7, 9, 13, 37));
		qService.create("진짜 정실", "명조의 딸\n그 이름 \"양양\"", LocalDateTime.of(2025, 7, 9, 13, 35));
		qService.create("파우웅은왜파우웅임?", "카르티시아는왜카르띳띠임? 본명임?", LocalDateTime.of(2025, 7, 9, 13, 33));
		qService.create("뉴비 리세계 사고 시작했는데 과금 관련해서 질문좀", "1. 월정액 5900원 짜리 + 초회만 일단 다깨면 됨? 딴거 더 살거 없음?\n2. 코스튬은 한정판매임? 다시 안팜?\n장리 카를로타 코스튬 다 사고 싶은데 캐릭터가 없으면 굳이 먼저 살 필요는 없음?\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 33));
		qService.create("핑챙 긴머리 여캐 내주세요", "나오면 꼭 풀돌할게요", LocalDateTime.of(2025, 7, 9, 13, 33));
		qService.create("명워웨", "명조워더링웨이브", LocalDateTime.of(2025, 7, 9, 13, 33));
		qService.create("방랑자가 여자는 꼬셔도 야스는 못 하는 이유가 이거구나", "이년이 온 지역에 날아다니는 cctv를 깔고 있는데 어케 해\n못된년", LocalDateTime.of(2025, 7, 9, 13, 31));
		qService.create("이 두 이벤트는 캐릭풀 적으면 그냥 포기해야 되는거임?", "죽음의 노래와 바닷속 폐허\n역경의 탑", LocalDateTime.of(2025, 7, 9, 13, 31));
		qService.create("이년들 왜 귀에 자부심 가지지", "걍 개징그러운데", LocalDateTime.of(2025, 7, 9, 13, 30));
		qService.create("파우웅이랑 첫키스맛 ㄹㅇ 레몬맛이래", "원하는 대로 맞춰준대", LocalDateTime.of(2025, 7, 9, 13, 30));
		qService.create("아 맘스땃쥐먹고깊네..", "흑흑", LocalDateTime.of(2025, 7, 9, 13, 30));
		qService.create("최신 플로로 테섭플레이영상 보면서 느낀게", "공명해방쓰고 지휘하는거보니까 ㅈㄴ 디테일하게 지휘하던데\n플로로가 죽인게 맞다\n근데 이쁘니까 괜찮음", LocalDateTime.of(2025, 7, 9, 13, 30));
		qService.create("파수인 오늘은 파워에이드로 싸줘", "온도는 차갑게", LocalDateTime.of(2025, 7, 9, 13, 29));
		qService.create("뉴비 질문 지금 겜 들어가기 좋음?", "뉴비 함 해볼려고 하는데 질문 드려봅니다\n1.\n해본겜이 블아밖에 없어서(타겜 언급 ㅈㅅ)\n보면 블아는 지금 여름 방학때 100연 + 페스 있어서 뉴비 복귀 타이밍 대놓고 주는데\n이겜은 그런거 있음? 뉴비 복귀 들어갈 유리한 타이밍 따로 있는지?\n2.\n가챠보니까 기간 한정으로 뽑기가 메인이던데\n복각 주기가 어떻게 되는지? 대충이라도\n3.\n0티어 1티어 캐 없으면\n아예 파티가 구성이 안되거나 보상을 못먹거나 그럼?\n아니면 클 시간이 늘거나 불편하기만 한 정도임?\n질문이 좀 많네 ㅎ", LocalDateTime.of(2025, 7, 9, 13, 29));
		qService.create("근데 스토리에서 금희 진짜 수상하게 계속 언급하네", "2.2부터 자꾸 수상하게 언급 계속 되는거 같은데\n진짜 다음버전 스카 잡으러 출동하는거야?", LocalDateTime.of(2025, 7, 9, 13, 29));
		qService.create("카멜리아 소속 좀 충격이네", "색깔만 보고 당연히 그쪽인 줄 알았는데", LocalDateTime.of(2025, 7, 9, 13, 28));
		qService.create("뉴비 스토리 밀면서 느낀점", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n카르티시아 유입인데 여긴 도시에 집착하는 이야기가 대부분인듯.. 좀 특이하다 느꼈음. 서양겜이나 한국겜은 좀 인간관계의 이야기가 많은데 중국겜은 항상 나라를 위해 희생하더라.\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 28));
		qService.create("플로로는 ㅅㅂ 세탁이 되긴 하냐?", "생체실험까지 해버리네 ㅋㅋㅋㅋㅋㅋㅋ\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 27));
		qService.create("날씨가 더워지니 루파를 보며 침흘리는 방랑자", "루파로 기력보충 할 계획이라고함", LocalDateTime.of(2025, 7, 9, 13, 26));
		qService.create("뉴비 리세계 ㄱㅊ함?", "요거 으떰?", LocalDateTime.of(2025, 7, 9, 13, 26));
		qService.create("플뢰르 변신했을때 딜사이클 보통 어케돌림?", "ㅇㅇ?", LocalDateTime.of(2025, 7, 9, 13, 26));
		qService.create("확실히 융용 물빨파티는 손가락차이인듯", "울립 탑4층 루장브 명전으로 13초컷내는거보고 할말을 잃었다", LocalDateTime.of(2025, 7, 9, 13, 26));
		qService.create("요즘은 에픽으로 결제해야 됨?", "겜 다시 깔아야 하는건가 귀찮네\n그래도 20프로 페이백이면 크긴 하네", LocalDateTime.of(2025, 7, 9, 13, 25));
		qService.create("이번 번역은 살짝 아쉽네", "\"의로운 자\"<-- 이게 뭔 개소리인가 했더니\n원문이 义无反顾임\nhttps://baike.baidu.com/item/%E4%B9%89%E6%97%A0%E5%8F%8D%E9%A1%BE/14937943\n义无反顾\n义无反顾（拼音：yì wú fǎn gù）是一个汉语成语，最早出自汉·司马相如《喻巴蜀檄》。该成语意思是从道义上只有勇往直前，不能犹豫回顾。该成语结构是主谓式，在句中作谓语、定语、状语；含褒义。\nbaike.baidu.com\n바이두 백과사전에서 보면\n\"뒤돌아보지 않고 용감하게 나아가라\"는\n뜻의 관용어구라고 함.\n드라마/영화/노래 제목으로 자주 쓰이는\n꽤 인지도 있는 말이라 할 수 있는데,\n외국에서는 임전무퇴 등의\n사자성어를 쓰면 썼지 왠만하면\n대응하는 말이 없는거 같더라고.\n일본어도 \"포기하지 않는 자\"\n영문도 \"흔들림 없이 나아가는 자\"\n로 다들 의역한거 보면\n애초에 직역으로는 힘든 단어같음.\n하 근데\n파파고 딸깍은 아니겠지....\n아닐거라 믿음.", LocalDateTime.of(2025, 7, 9, 13, 24));
		qService.create("이제 그만하자노", "좀 내보내달라고 씨발련아", LocalDateTime.of(2025, 7, 9, 13, 23));
		qService.create("파우웅 무서운점은 그거임...", "필드에서 잘 놀고 스토리 밀고 하다가\n이따금씩 파랗게 빛나는 나비가 있다는걸 눈치챔\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 23));
		qService.create("명조 해외랑 한국이랑 먼가 비슷하구나", "한 게임 팬덤에서 공격하는게 해외나 한국이나 똑같아", LocalDateTime.of(2025, 7, 9, 13, 23));
		qService.create("파수인<<똥구멍 있음?", "중요함", LocalDateTime.of(2025, 7, 9, 13, 23));
		qService.create("이 십새끼들은 왜 wwe만 함?", "나랑 싸울 때는 몇 천 딜을 가볍게 욱여넣으면서", LocalDateTime.of(2025, 7, 9, 13, 21));
		qService.create("아 진짜 장리 때문에 게임 못하겠네 ㅅㅂ;;", "개꼴려서 딸치느라 게임에 집중이 안되네;;", LocalDateTime.of(2025, 7, 9, 13, 21));
		qService.create("진실은 탈옥이 아닐수도 있는것", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n구해주러 갔다가 묑한테 개쳐맞고 리나시타로 도망와선 시나리오속 가상인물로 스카가 탈출한것 처럼 위안을 얻은것 뿐일거임\n스카는 아직 지하감옥에 있다. 즉, 그뫼엥은 거품이 아니란 거임", LocalDateTime.of(2025, 7, 9, 13, 21));
		qService.create("파우웅<<<<비콘 놓아줌, 관리도 해줌", "", LocalDateTime.of(2025, 7, 9, 13, 20));
		qService.create("안녕하세요. 오늘은 유두절입니다.", "띵갤 이용자 분들께서는 유두사진을 많이 올려주시길 바랍니다.", LocalDateTime.of(2025, 7, 9, 13, 19));
		qService.create("님들양산쓰고다님?", "도저히 그냥 못다니겠는데", LocalDateTime.of(2025, 7, 9, 13, 19));
		qService.create("만약 제가 수좌가 된다면", "모든 페비까들을 다 순례선 태우겠습니다 감사합니다", LocalDateTime.of(2025, 7, 9, 13, 18));
		qService.create("금희<-활공으로 억까 오지게 당함", "파수인도 활공금지 하는데 금희만 까임", LocalDateTime.of(2025, 7, 9, 13, 18));
		qService.create("수호신 공명자들이 재밌지는않은거같음", "올컬렉인데 딜하고는 별개로 파티단위로보면\n금희 띳띠 얘네가 제일루즈함\n용융 카를 젠니는 꿀잼이고 기염 상음도 재미는ㄱㅊ\n카멜이 애매한데 갠적으로 그미띳띠보단 나은듯\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 17));
		qService.create("이런 날씨에 루파한테 무슨 냄새남???", "ㅇㅇ", LocalDateTime.of(2025, 7, 9, 13, 16));
		qService.create("아오 융융용용융용용융팟 놈들아", "장브루 루브장 장루브 브루장 하나만 하라고", LocalDateTime.of(2025, 7, 9, 13, 15));
		qService.create("명워웨 브금이 맛있지는 않은듯", "개인적으로 기억에 남는건\n파수인 피아노 연주\n이거밖에 없음\n맵 브금은 좋은게 딱히 안떠오르네\nㄱㅊ은거 잇스면 추천점", LocalDateTime.of(2025, 7, 9, 13, 14));
		qService.create("내 카르티시아 스팩 왜 이럼?", "좀 많이 열받네 크피 왜 이렇게 낮음\n일공피 18 공해피 38임", LocalDateTime.of(2025, 7, 9, 13, 14));
		qService.create("리나시타 들어가면 맵탐사 편해짐?", "활공이 그럭게 goat임??", LocalDateTime.of(2025, 7, 9, 13, 14));
		qService.create("역시 유노야ㅠㅠㅠㅠ", "", LocalDateTime.of(2025, 7, 9, 13, 13));
		qService.create("중앙탑이 명함 상시무기로 3별이 불가능한거 아니지?", "그러니까 이번은 기류 용융 저항 10퍼 깎고 풍식 접대인데\n용융팀으로 가도 할만하지 않음?", LocalDateTime.of(2025, 7, 9, 13, 13));
		qService.create("카르티시아는 진짜 혁명적인 캐릭터이긴 함", "키 2.5m / 체중 170kg 여캐를\n매니악한 거인 패티쉬가 아니라 정실 급으로 호불호 없이 밀어준다?\n이거 이제까지 없었던 시도거든요\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 13));
		qService.create("너네 유노랑 무인도에 가둘거야", "나체로", LocalDateTime.of(2025, 7, 9, 13, 12));
		qService.create("시스템상 온필드 긴 딜러는 못나오려나", "온필드 한 80퍼이상 가져가면서 혼자 회피하고 할거 다하는거 좋아하는데\n변주반주 시스템상 밸런싱이 힘들어서 + 장사안돼서 안나오겠네\n답은 당근솔플뿐인가", LocalDateTime.of(2025, 7, 9, 13, 12));
		qService.create("명조 진짜 어렵다", "통통튀는 공룡 2마리 한번에나오는거 잡다가 마우스던질뻔", LocalDateTime.of(2025, 7, 9, 13, 11));
		qService.create("띳또그콘 쓸수록 지능이 떨어진다고함…", "무분별한 띳또그콘 당장 멈춰야", LocalDateTime.of(2025, 7, 9, 13, 11));
		qService.create("나 고백할거 있어 띵붕아", "아직 스토리 안밀엇어", LocalDateTime.of(2025, 7, 9, 13, 11));
		qService.create("테토남이긴 함", "테토를 좋아하는 남자", LocalDateTime.of(2025, 7, 9, 13, 10));
		qService.create("앞으로 풀돌하는 캐릭은", "파츠 안뽑아야지... 파츠가 의미가 없는듯... 풀돌이먼\n.......\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 10));
		qService.create("명조하는 테토남특징", "명조세계관에 미소녀로 ts빙의해서 남성성을 지켜보려 하지만 방은우를 만나고 서서히 함락 당해서 하렘편입 당하는 역할이래\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 10));
		qService.create("스토리 이제야 다 밀엇는데", "스포일러 경고 기능이 추가됐습니다.\n(\n설정\n에서 변경 가능)\n보스전 브금이랑 컷신때 노래 들어가는거 아직도 어색하네\n1버전땐 이런거 꿈도 못꿧는데 엄청 성장햇다 명조 ㄹㅇ...", LocalDateTime.of(2025, 7, 9, 13, 9));
		qService.create(".........", "", LocalDateTime.of(2025, 7, 9, 13, 9));
		qService.create("페비 새알심 뒤지게 귀엽네", "삣삐쮸삐 이지랄할때마다 귀여워죽것슴\n입에 넣고 하루종일 굴리고싶네", LocalDateTime.of(2025, 7, 9, 13, 9));
		qService.create("치사만 2돌하고 이제 돌파 멈출까", "사실 산호로 가챠권 쌀먹하는거도 꽤 달달한데 돈아끼는 면에서는", LocalDateTime.of(2025, 7, 9, 13, 9));
		qService.create("영원을 지켜라 입구어디야 대체", "퀘스트하다가 빡세서 나중에할려고 그냥 나왔는데\n오늘하려고 들어가보니 입구자체가 어딘지모르겠어 어디야?ㅠㅠ", LocalDateTime.of(2025, 7, 9, 13, 9));
		qService.create("근데 카르티시아 파티가 그렇게 재밌는편은아님?", "샤콘리세계 2.4유입이라 얘밖에 없어서그러는데\n카샤기가 명조 전체파티중에 재미로 상위권은아님???\n뭔가 플레이체감 얘기나오는거보면 재밌다는쪽에 잘안뽑히는거같네\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 6));
		qService.create("명조 하는데 테토남이면 뭐임", "나말하는거맞음\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 5));
		qService.create("가챠 계획 어떻게 하지", "음림 명전\n금희 명전\n장리 명함\n파수인 명함\n샤콘 명전\n카르띳띠 풀돌 전무\n픽업캐들 이렇게 있는데 기류팟 밖에 완성이 안되서 브랜트 없더라도 루파 데려가서 불파티 만들지, 신캐 중에 메인딜러 새로 뽑아서 파츠 맞춰가면서 길게 볼지 고민임", LocalDateTime.of(2025, 7, 9, 13, 4));
		qService.create("파수인이랑 카멜리아 중에 누가 더 늙음?", "누가 더 연식 오래됨", LocalDateTime.of(2025, 7, 9, 13, 3));
		qService.create("퀵스왑 하고 안하고 차이가 그렇게 큼?", "유튭보는데 명전 루파 앙코 모르테피로 중앙탑 56초 머임\n난 풀돌 장리로 50초 나오는데", LocalDateTime.of(2025, 7, 9, 13, 3));
		qService.create("스토리 컷신 | 마지막 경기", "https://youtu.be/YajJUs4R79s?si=HPX5ukWH8QddHY3i", LocalDateTime.of(2025, 7, 9, 13, 0));
		qService.create("기랑자 공효 뭐가 맞는거임?", "150 200 250 존나 다양한데\n뭐가맞음..걍 딜생각없고 땃띠 싸개할껀디..\n- dc official App", LocalDateTime.of(2025, 7, 9, 13, 0));
		qService.create("와 카페들어갔는데 가슴 보여서 깜짝 놀램", "마켓팅인지\n가슴 존나 큰사람이 반 보이게 입고 커피내려줌 ㄷㄷ", LocalDateTime.of(2025, 7, 9, 13, 0));
		qService.create("예전에 언니겜 돌계사느라 타오바오 뚫었었는데", "지금너무 잘쓰고있어서 큰일임", LocalDateTime.of(2025, 7, 9, 12, 58));
		qService.create("기랑자 공효 몇해줌?", "4코1코 크리크피는 됐는데 이제 3코 해야하는데", LocalDateTime.of(2025, 7, 9, 12, 58));
		qService.create("얘는 진짜 몸이 애기같네…", "이런 애기같은 몸으로 애기 어케 낳지", LocalDateTime.of(2025, 7, 9, 12, 57));
		qService.create("내가 죽였냐?", "잔상이 죽였지.\n내가 죽였냐?\n총알이 죽였지\n내가 죽였다.\n뭐.\n- dc official App", LocalDateTime.of(2025, 7, 9, 12, 57));
		qService.create("니 아내임", "니 아내임", LocalDateTime.of(2025, 7, 9, 12, 56));
		qService.create("어이 씨발련!!", "우으 안녕..", LocalDateTime.of(2025, 7, 9, 12, 56));
		qService.create("리세계 이거는 어떰?", "10만원인데 젠+페 조합은 매물이 많은데\n파수인까지 껴있는건 얘가 유일한듯\n타오바오까지 다 뒤져봤는데 젠페 + 파 까지 하려면 이게 유일한거 같은데\n이걸로 갈까?", LocalDateTime.of(2025, 7, 9, 12, 54));
		qService.create("그래도 카멜이 절지 페비보다는 이쁨", "아닌가?", LocalDateTime.of(2025, 7, 9, 12, 54));
		qService.create("아니 갤 서로 반대로 글 썼네", "진짜 개삣삔가", LocalDateTime.of(2025, 7, 9, 12, 54));
		qService.create("겜 3개하는데 전부다사랑해여", "그중에서 띵조를 제일 좋아함미다.. 로로돌파할라고 돌도 미리삿어여\n- dc official App", LocalDateTime.of(2025, 7, 9, 12, 53));
		qService.create("그래서 줄리아가 루파 배신한이유가 뭐야???", "그냥 얼렁뚱땅 넘어가는거 같은데 아님 내가 제대로 못봤나 이유 아는사람 있노???\n- dc official App", LocalDateTime.of(2025, 7, 9, 12, 53));
		qService.create("명조가 재화를 많이 주는건가", "붕스가 적게 주는건가\n후반인데 벌써 50뽑이상 모았네 후반 시작하자마자 루파 명전에 다쓰고 0이었는데", LocalDateTime.of(2025, 7, 9, 12, 52));
		qService.create("카멜리아 뽑고싶다", "전임할때 얘 조작할때가 제일 재밌는데", LocalDateTime.of(2025, 7, 9, 12, 52));
		qService.create("방금 명조로 오르가즘 느꼈음", "", LocalDateTime.of(2025, 7, 9, 12, 52));
		qService.create("루파 방 빼라고?", "지금 파트너들 이해를 못하시나본데, 명전 안뽑으시면 방 못뺀다니까?", LocalDateTime.of(2025, 7, 9, 12, 52));
		qService.create("클릭시 짤녀가 사는도시에서만 게임해야함", "어서오세요.", LocalDateTime.of(2025, 7, 9, 12, 51));
		qService.create("피삐피삐피삐~", "", LocalDateTime.of(2025, 7, 9, 12, 51));
		qService.create("뇌에에에에에에엥~~", "", LocalDateTime.of(2025, 7, 9, 12, 51));
		qService.create("근데 왜 명갤에서 다른게임콘 쓰는거임?", "띵조콘써!", LocalDateTime.of(2025, 7, 9, 12, 50));
		qService.create("유노가 말할때 무조건 하는 말은?", "you know?ㅋㅋㅋㅋ", LocalDateTime.of(2025, 7, 9, 12, 50));
		qService.create("이번 스토리 얼마나걸림??", "한 세시간잡고하면되나", LocalDateTime.of(2025, 7, 9, 12, 50));
		qService.create("여기서 갑자기 난이도 다크소울되버리네", "원빵나는건 에바지", LocalDateTime.of(2025, 7, 9, 12, 49));
		qService.create("???:내가 죽였어. 일인데 뭐 어떡하라구??", "아니 잔성회 근무인걸 나보고 어쩌라고? 그래 죽였어! 나도 벌어먹고 살아야지! 돈 벌기 힘들어!!", LocalDateTime.of(2025, 7, 9, 12, 49));
		qService.create("나는 카멜팟 재밋던데 평이별로네", "오히려 카를이 좀 많이 단조로워서 그닥이엇고\n젠니 타격감이랑 카멜이 좀 재밋던데\n장브루 용융도 할만하고\n카르티시아는 그냥그럼..", LocalDateTime.of(2025, 7, 9, 12, 48));
		qService.create("카르티시아 테마노래 멜로디가 왜캐 익숙하지", "그 점점 음 올라가는파트가 왜캐 어디선가 한번 들어본거같은 멜로딘데 미치겠네 어디서들은건지 모르겠어", LocalDateTime.of(2025, 7, 9, 12, 47));
		qService.create("표정개꼴받게생겼네ㅅㅂ", "남은한쪽눈도 안대쓰게해주고싶음", LocalDateTime.of(2025, 7, 9, 12, 47));
		qService.create("기랑자 샤콘 퀵스왑 연습하다가보니까", "필드에서 페비로 날아가서 기랑자 샤콘만 돌려가면서 몹잡고있는 나를 발견...\n은근히 중독성있다 이거... ㅋㅋㅋ;;\n참 어제 샤콘 낙공 설명해준사람 고마워", LocalDateTime.of(2025, 7, 9, 12, 46));
		qService.create("오늘은 누구 에코작할까~¿?¿?", "저항도못하고 나한테 옵티마이징 당할 공명자 누구야", LocalDateTime.of(2025, 7, 9, 12, 46));
		qService.create("아니 너무 추워", "20도는 에바 아니냐", LocalDateTime.of(2025, 7, 9, 12, 46));
		qService.create("홀로그렘 6별 질문", "시간 부족으로 못깨는거 아니면 똥컨이슈겠죠..?\n스치면 죽으니깐 혈압올라 죽을거같음\n- dc official App", LocalDateTime.of(2025, 7, 9, 12, 45));
		qService.create("플로로같이 분탕치고 사람 죽인 나쁜 아이는 용서못함", "개좆로 이씨발 띵갤의악의축", LocalDateTime.of(2025, 7, 9, 12, 45));
		qService.create("ㄴ띳도그 투하", "", LocalDateTime.of(2025, 7, 9, 12, 45));
		qService.create("샤아아악", "", LocalDateTime.of(2025, 7, 9, 12, 45));
		qService.create("ㄴ카르띳띠 얘기면 딸치러감", "- dc official App", LocalDateTime.of(2025, 7, 9, 12, 44));
		qService.create("아점 로제떡볶이vs생크림토스트vs마라탕", "뭐 먹을까", LocalDateTime.of(2025, 7, 9, 12, 43));
		qService.create("치사가 플로로 파츠임??", "치사도 인멸로 나옴?\n플로로 칸타 로코코 파티하려 했는데\n치사도 뽑을거라 음...", LocalDateTime.of(2025, 7, 9, 12, 43));
		qService.create("뉴비 오늘 생일이야", "생일이라고 왕관까지 주네", LocalDateTime.of(2025, 7, 9, 12, 43));
	}

}
